[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all]>=0.116.2",
    "passlib[bcrypt]>=1.7.4",
    "psycopg[binary]>=3.2.10",
    "python-jose>=3.5.0",
    "sqlmodel>=0.0.25",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
backend = { workspace = true }

[dependency-groups]
dev = [
    "backend",
]
